exports.ResultTypeEnum = {
  DISPLAY: "DISPLAY",
  JSON: "JSON",
  TEXT: "TEXT",
  DISPLAY_PRODUCT: "DISPLAY_PRODUCT",
  DISPLAY_ORDER_DETAIL: "DISPLAY_ORDER_DETAIL",
  DISPLAY_REVENUE: "DISPLAY_REVENUE",
};
