import { REGISTER } from "redux-persist";

const path = {
  PUBLIC: "/",
  HOME: "",
  ALL: "*",
  LOGIN: "login",
  REGISTER: "register",
  REGISTER_SHOP: "register-shop",
  PRODUCTS__CATEGORY: ":category",
  BLOGS__ID__TITLE: "blogs/:id/:title",
  BLOGS: "blogs",
  OUR_SERVICES: "services",
  FAQ: "faqs",
  DETAIL_PRODUCT__CATEGORY__PID__TITLE: ":categoryName/:slug",
  RESET_PASSWORD: "reset-password/:token",
  DETAIL_CART: "my-cart",
  CHECKOUT: "checkout",
  PRODUCTS: "products",
  SEARCH_HOME: "tat-ca-san-pham",
  SHOP: "shops",
  CART: "carts",
  ORDER: "orders",

  // Admin
  ADMIN: "admin",
  A_DASHBOARD: "dashboard",
  A_MANAGE_USERS: "manage-users",
  A_MANAGE_BLOCK_USERS: "manage-block-users",
  A_MANAGE_SHOPS: "manage-shops",
  A_MANAGE_BLOCK_SHOPS: "manage-block-shops",
  A_MANAGE_COUPONS: "manage-coupons",
  A_MANAGE_SERVICE_PLAN: "manage-service_plans",
  A_MANAGE_CATEGORY: "manage-categorys",
  A_MANAGE_BRANDS: "manage-brands",

  DASHBOARD: "dashboard",
  MANAGE_USER: "manage-user",
  MANAGE_PRODUCTS: "manage-products",
  MANAGE_ORDER: "manage-order",
  CREATE_PRODUCTS: "create-products",
  CREATE_BLOG: "create-blog",
  MANAGE_BLOGS: "manage-blogs",
  CREATE_VARIATION: "/admin/create-variation/:productId",
  MANAGE_PRODUCTS_CATEGORIES: "manage-products-categories",
  MANAGE_BRANDS: "manage-brands",
  MANAGE_COUPONS: "manage-coupons",

  //Customer
  CUSTOMER: "customer",
  C_PROFILE: "profile",
  C_ADDRESS: "addreeses",
  C_ORDER: "orders",
  C_SUCCEEDED_ORDER: "succeeded-orders",
  C_MANAGESELLER: "manage-seller",

  //Shop
  SELLER: "seller",
  S_PROFILE: "profile",
  S_ADDRESS: "addreeses",
  S_ORDER: "manage-orders",
  S_MANAGE_COUPONS: "manage-coupons",
  S_CANCEL_ORDER: "manage-cancel-orders",
  S_MANAGE_PRODUCTS: "manage-products",
  S_CREATE_PRODUCT: "create-product",
  S_MANAGE_CATEGORIES: "manage-categories",
  S_CREATE_CATEGORIES: "create-category",
  S_DASHBOARD: "dashboard",
};

export default path;
